=== MartinMiller/SouthParkDownloader/data/players.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		xmlns="https://github.com/craue/SouthParkDownloader"
		targetNamespace="https://github.com/craue/SouthParkDownloader"
		elementFormDefault="qualified">
	<xs:element name="players">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="player">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="swfurl" type="xs:string" minOccurs="0" />
							<xs:element name="swfsize" type="xs:string" minOccurs="0" />
							<xs:element name="swfhash" type="xs:string" minOccurs="0" />
						</xs:sequence>
						<xs:attribute name="latest" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MartinMiller/SouthParkDownloader/data/players.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
	Player database.
	This file is part of the South Park Downloader package.

	Author: Christian Raue <christian.raue@gmail.com>
	Copyright: 2011 Christian Raue
	License: http://www.gnu.org/licenses/gpl-3.0.html GPLv3 License
-->
<players xmlns="https://github.com/craue/SouthParkDownloader"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="https://github.com/craue/SouthParkDownloader players.xsd">
	<player>
		<swfurl>http://media.mtvnservices.com/player/release/?v=4.3.0</swfurl>
		<swfsize>608633</swfsize>
		<swfhash>79190891927d9925a6a53f7a6bdce7b9e879087a94cd6fd66ac0135622ef18e8</swfhash>
	</player>
	<player>
		<swfurl>http://media.mtvnservices.com/player/release/?v=4.5.3</swfurl>
		<swfsize>933967</swfsize>
		<swfhash>4506d4a6b8ad72c7946bf063a3599896e52ee46bb7d6f1a8d7e0f9d661284c30</swfhash>
	</player>
	<player>
		<swfurl>http://media.mtvnservices.com/player/prime/mediaplayerprime.1.7.0.swf</swfurl>
		<swfsize>1983727</swfsize>
		<swfhash>0884b06decee5e866a24792f198b4b88f7232e9da92f1e5520ca330822f0d4f9</swfhash>
	</player>
	<player>
		<swfurl>http://media.mtvnservices.com/player/prime/mediaplayerprime.1.8.5.swf</swfurl>
		<swfsize>2016733</swfsize>
		<swfhash>912124fbd031df42f2ccbdefb8f1224de2f31a15503c98be1fcf1a5e501dcfbb</swfhash>
	</player>
	<player latest="true">
		<swfurl>http://media.mtvnservices.com/player/prime/mediaplayerprime.1.9.2.swf</swfurl>
		<swfsize>2022384</swfsize>
		<swfhash>4dc6a9e1db35a9c89c380015af28fe80cd7acd259af63315202a50cac7999b05</swfhash>
	</player>
</players>
